title: Keystone Masonry, LLC
description: >-
  Keystone Masonry, LLC
baseurl: ""
url: "https://keystonemasonryks.com"
port: 4003
ga_tracking_id: UA-138753823-1

# Social and Contact
github_url: https://github.com/heatherpekrul/keystonemasonry
facebook_url: PLACEHOLDER
email: heather.pekrul@gmail.com
phone: 785-123-4567
address_line: 3910 NE Croco Road
address_city: Topeka, KS
address_zip: 66617
address_country: US

# Footer
footer:
  copyright: Copyright 2019 Keystone Masonry, LLC. All rights reserved.

# Build settings
markdown: kramdown

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - js/
  - scss/
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
