title: Keystone Masonry, LLC
description: >-
  Keystone Masonry, LLC
baseurl: ""
url: "https://keystonemasonryks.com"
port: 4003
ga_tracking_id: UA-138753823-1

# Social and Contact
github_url: https://github.com/heatherpekrul/keystonemasonry
facebook_page: keystonemasonryks
email: contact@keystonemasonryks.com
phone: 785-640-5624
address_line:
address_city: Topeka
address_state: KS
address_zip: 66617
logo_image: images/keystone-masonry-logo-square.jpg

# Footer
footer:
  copyright: Copyright 2019 Keystone Masonry, LLC. All rights reserved.

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-inline-svg
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - js/
  - scss/
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
